### PR TITLE
Better XML serialization 

### PR DESCRIPTION
**Pull request by mqnifestkelvin**
Good morning  @pgleeson 
Apologies for the many branches and pull requests. I've been testing and trying to make the code handling much better in handling serialization especially when converting back to a Python dictionary. I will take down the previous PR and put this one forward to be merged. 
Thank you and apologies for the delay.

### CODE REVIEW

**Comment by mqnifestkelvin** [comment]
@pgleeson good day, I will check out the codes and see why it's failing the checks.
I also merged the PR you made earlier to the branch. 
I also noticed the new class you created, I will use that to test the xml serialization to see if it represents exactly without change the contents in comparison with the one generated by neuroml

**Comment by pgleeson** [comment]
Great @mqnifestkelvin. Note, I'd suggest concentrating first on getting the tests passing and getting the current  form of the XML exportable/imporrtable, before making changes related to use of attributes in NeuroML.

**Comment by pgleeson** [comment]
I assume this is out of date now

**Comment by mqnifestkelvin** [comment]
Hello @pgleeson yes this is out of day the feature_xml_3 is the most current one for now

**Pull request closed without merging**
