### PR TITLE
Generated sphinx documentations for the modelspec library

### PR DESCRIPTION
**Pull request by mqnifestkelvin**
Hello mentors,

I have successfully generated sphinx documentations for the mdelspec library I hope this was your expectation and if it isn't,  I'd try again with your guidance and help, thank you.

### CODE REVIEW

**Comment by mqnifestkelvin** [comment]
I also took the liberty of adding missing docstrings in the utils script.

**Comment by pgleeson** [comment]
Can you remove the _build directory from this PR @mqnifestkelvin? All those files will be regenerated when anyone builds it.

**Comment by mqnifestkelvin** [comment]
Good morning, I will do this right away.

**Comment by pgleeson** [comment]
As mentioned @mqnifestkelvin, if there's anything here that's not in the current documentation for modelspec, please let us know, otherwise we can close this PR.

**Pull request closed without merging**
